# Generated by Django 5.0.7 on 2024-08-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_image_is_primary_alter_group_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/comments'),
        ),
    ]
