# Generated by Django 5.0.7 on 2024-08-10 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_comment_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute_key',
            old_name='key_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='attribute_value',
            old_name='value_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='app.product'),
        ),
    ]
